server:
  port: 8080
spring:
  application:
    name: company-frame
  #数据库配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/company_frame?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=true
      username: root
      password: admin123

      ##################   连接池配置   ################
      #连接池建立时创建的初始化连接数
      initial-size: 5
      #连接池中最大的活跃连接数
      max-active: 20
      #连接池中最小的活跃连接数
      min-idle: 5
      # 配置获取连接等待超时的时间
      max-wait: 60000
      max-pool-prepared-statement-per-connection-size: 20
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      validation-query: SELECT 1 FROM DUAL
      query-timeout: 30000
      #是否在获得连接后检测其可用性
      test-on-borrow: false
      #是否在连接放回连接池后检测其可用性
      test-on-return: false
      #是否在连接空闲一段时间后检测其可用性
      test-while-idle: true
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall

  #redis配置开始
  redis:
    # Redis服务器地址
    host: localhost
    # Redis服务器连接端口
    port: 6379
    #Redis服务器连接密码（默认为空）
    password:
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 1024
        # 连接池最大阻塞等待时间（使用负值表示没有限制）10秒
        max-wait: PT10S
        # 连接池中的最大空闲连接
        max-idle: 200
        # 连接池中的最小空闲连接
        min-idle: 0
    # 连接超时时间（10秒）
    #"PT20.345S" -- parses as "20.345 seconds"
    #"PT15M"     -- parses as "15 minutes" (where a minute is 60 seconds)
    #"PT10H"     -- parses as "10 hours" (where an hour is 3600 seconds)
    #"P2D"       -- parses as "2 days" (where a day is 24 hours or 86400 seconds)
    #"P2DT3H4M"  -- parses as "2 days, 3 hours and 4 minutes"
    #"PT-6H3M"    -- parses as "-6 hours and +3 minutes"
    #"-PT6H3M"    -- parses as "-6 hours and -3 minutes"
    #"-PT-6H+3M"  -- parses as "+6 hours and -3 minutes"
    timeout: PT10S
  #解决 spring boot devtool 热部署后出现访问 404 问题
  devtools:
    restart:
      poll-interval: 3s
      quiet-period: 2999ms

#logging配置
logging:
  file:
    path: logs
    name: ${logging.file.path}/${spring.application.name}.log
  level:
    com:
      yingxue:
      lesson: info

#加入以下配置 对应生成 mapper.xml 的路径
mybatis:
  mapper-locations: classpath:mapper/*.xml

#swagger 开关
swagger2:
  enable: true

#JWT 密钥
jwt:
  secretKey: SaberKing51666fg)
  accessTokenExpireTime: PT2H
  refreshTokenExpireTime: PT8H
  refreshTokenExpireAppTime: P30D
  issuer: yingxue.com

#pagehelper 配置方言和分页合理化
pagehelper:
  helperDialect: mysql
  reasonable: true