spring:
  application:
    name: company-frame
  profiles:
    active: dev

  # 解决 spring boot devtool 热部署后出现访问 404 问题
  devtools:
    restart:
      poll-interval: 3s
      quiet-period: 2999ms

  # thymeleaf
  thymeleaf:
    # 前缀 默认读取classpath:/templates/
    #prefix: classpath:/templates/
    # 后缀 默认.html
    #suffix: .html
    # 编码 默认 UTF-8
    #encoding: UTF-8
    # 默认 text/html
    #servlet:
    #content-type: text/html
    cache: false

# 加入以下配置 对应生成 mapper.xml 的路径
mybatis:
  mapper-locations: classpath:mapper/*.xml

# swagger 开关
swagger2:
  enable: true

# pagehelper 配置方言和分页合理化
pagehelper:
  helperDialect: mysql
  reasonable: true